### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by Birowsky** [jlagerweij/elm-external-tools#4]
Hey there, after a month of usage, I have these two strange patterns happening:

- The plugin crashes and I need to restart WebStorm to have it work again.
- Every time I start WebStorm, I also need to start the plugin:
<img width="788" alt="screen shot 2018-04-01 at 12 03 54" src="https://user-images.githubusercontent.com/3199950/38172032-238c708e-35a5-11e8-9021-cde8ef2e83f9.png">

Can I provide you with some tech logs/details so It could help you investigate?

**Comment by jlagerweij** [comment]
In the idea.log there might be some logging / exceptions. Find it in IntelliJ by using Help -> Show logs.

**Comment by Birowsky** [comment]
Deal. Will report back when it crashes again.

**Comment by Birowsky** [comment]
Here are the logs of two times right before it crashed:

```
2018-04-07 01:34:07,820 [ 984666]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@7e119433] 
2018-04-07 01:34:15,611 [ 992457]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png 
2018-04-07 01:34:15,985 [ 992831]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 72 to update, calculated in 6ms 
2018-04-07 01:34:16,082 [ 992928]   INFO - .diagnostic.PerformanceWatcher - Reindexing refreshed files took 97ms; general responsiveness: ok; EDT responsiveness: ok 
2018-04-07 01:34:27,619 [1004465]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/Schema.elm 
2018-04-07 01:34:35,962 [1012808]   INFO - openapi.wm.impl.PaintersHelper - (CGLGraphicsConfig) 1440x900 accelerated volatile image created 
2018-04-07 01:34:51,494 [1028340]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@183cf787] 
2018-04-07 01:36:04,271 [1101117]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png 
```

```

2018-04-07 13:27:39,031 [42424981]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/Job.elm 
2018-04-07 13:27:43,627 [42429577]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/Job.elm 
2018-04-07 13:27:45,978 [42431928]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/Job.elm 
2018-04-07 13:27:48,762 [42434712]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@5417a06] 
2018-04-07 13:28:23,515 [42469465]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/SampleData.elm 
2018-04-07 13:28:29,054 [42475004]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@55db76dd] 
2018-04-07 13:28:44,789 [42490739]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/SampleData.elm 
2018-04-07 13:29:05,742 [42511692]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/SampleData.elm 
2018-04-07 13:29:07,839 [42513789]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@54f00d0a] 
2018-04-07 13:29:14,168 [42520118]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@3ea41459] 
2018-04-07 13:30:01,613 [42567563]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/Schema.elm 
2018-04-07 13:30:29,307 [42595257]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@3cdbe7d] 
2018-04-07 13:30:34,820 [42600770]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@51385a15] 
2018-04-07 13:30:35,259 [42601209]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 73 to update, calculated in 24ms 
2018-04-07 13:30:35,335 [42601285]   INFO - .diagnostic.PerformanceWatcher - Reindexing refreshed files took 76ms; general responsiveness: ok; EDT responsiveness: ok 
2018-04-07 13:30:54,981 [42620931]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/Job.elm 
2018-04-07 13:31:05,616 [42631566]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/GraphqlSchema/Object/Completed.elm 
2018-04-07 13:31:11,540 [42637490]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/Schema.elm 
2018-04-07 13:31:23,616 [42649566]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Model/Job.elm 
2018-04-07 13:31:31,273 [42657223]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/Schema.elm 
2018-04-07 13:31:36,956 [42662906]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@6d2e4fd0] 
2018-04-07 13:31:36,998 [42662948]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@2c8411e0] 
2018-04-07 13:32:01,522 [42687472]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/Schema.elm 
2018-04-07 13:32:10,951 [42696901]   INFO - rnal.ElmExternalToolsComponent - /usr/local/bin/elm-make --report=json --output=/dev/null --yes --warn /MY-MASKED-PROJECT-PATH/src/scripts/Api/Schema.elm 
2018-04-07 13:32:13,919 [42699869]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Run) or icon Layered icon. myIcons=[jar:file:/Users/Birowsky/Library/Application%20Support/WebStorm2018.1/Material%20Theme/lib/material-theme-jetbrains-2.1.5.3.jar!/icons/toolwindows/toolWindowRun.png, com.intellij.execution.runners.ExecutionUtil$2@3203fce6] 
```

**Comment by jlagerweij** [comment]
There's no error in the logs, so no real help there. I do see the wrong settings in my own environment, but can't really tell why and when this is happening, yet. Will investigate further.

**Comment by jlagerweij** [comment]
Jetbrains notified me the update was approved. You can update to version 1.2 for this fix.

**Comment by Birowsky** [comment]
Cool beans. Thanx!

**Comment by Birowsky** [comment]
This happened just now:

<img width="963" alt="screen shot 2018-04-13 at 01 28 51" src="https://user-images.githubusercontent.com/3199950/38709213-12aad0bc-3eba-11e8-96a1-0d78f77b8743.png">


```

Invalid range specified: (-1, -1); 
java.lang.Throwable: Invalid range specified: (-1, -1); 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:229)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:224)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:220)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
	at org.elm.tools.external.annotator.ElmMakeExternalAnnotator.findAnnotationLocation(ElmMakeExternalAnnotator.java:152)
	at org.elm.tools.external.annotator.ElmMakeExternalAnnotator.annotateForIssue(ElmMakeExternalAnnotator.java:119)
	at org.elm.tools.external.annotator.ElmMakeExternalAnnotator.apply(ElmMakeExternalAnnotator.java:114)
	at org.elm.tools.external.annotator.ElmMakeExternalAnnotator.apply(ElmMakeExternalAnnotator.java:30)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:193)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.a(ExternalToolPass.java:158)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:156)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:382)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jlagerweij** [comment]
The Invalid range will be fixed in the upcoming 1.3.0 release of the plugin. Thank you for reporting these bugs!

**Comment by Birowsky** [comment]
Heh, no problemo :}

**Comment by Birowsky** [comment]
It is unfortunately still crashing. I still don't see anything useful in the logs tho. Please let me know if I can help debugging in any way.

**Comment by jlagerweij** [comment]
When you say crashing, what does that mean? Does it stop functioning? Does it print any stacktrace in the logs or in the IDE panel?

**Comment by Birowsky** [comment]
It just stops functioning, and I can't pinpoint when exactly. I just realize it along the way.

What is the IDE panel? :}

**Comment by jlagerweij** [comment]
There might be some stacktrace in the idea.log file. There might also be some logging the IDE, just like the screenshot you posted earlier. I am hoping for some more information to pinpoint how to fix the crashing part.

**Comment by Birowsky** [comment]
Every time this happens, I check the idea.log file, never seen a crash stack trace. Even the IDE doesn't show any info, the plugin just stops working.

But there is one case in which I think the problem is persistent:
I have configured elm-format as a file watcher:
<img width="1040" alt="screen shot 2018-05-01 at 02 03 39" src="https://user-images.githubusercontent.com/3199950/39456017-ec16ea2a-4ce3-11e8-8fbf-1e5db346edf2.png">


I also use [GraphqElm](https://github.com/dillonkearns/graphqelm). Now, every time I run `graphqelm` from the cli this problem occurs. When I run that command, multiple elm files are created/edited. That is causing multiple elm-format triggers, and those might be interfering with the same compilation process that your plugin uses.. just wild guesses here..

**Comment by jlagerweij** [comment]
I have not been able to reproduce the behaviour. For the last few weeks I have been working on Elm code, without any issue. I have elm-format configured aswel, so that should not be a problem. Even tested with the GraphqElm, but only for a short amount of time.

**Comment by Birowsky** [comment]
Damn. Just let me know if there's something you think I should try. Or if you want to check it on my machine, feel free to get in touch!

**Comment by jlagerweij** [comment]
I just released version 2.0.1, which can better notify the user if something fails when running 'elm make'. I hope this will help you a bit. This version also supports Elm 0.19 and requires a configuration change. It now longer uses elm-make, but uses the elm binary and executes 'elm make' instead. Let me know if this new version works any better.

**Comment by Birowsky** [comment]
Those are great news! It means I'll be able to provide you with some useful info next time it crashes. Thanx!

**Comment by Birowsky** [comment]
It keeps behaving the same way. Just stops working after a while, but I don't get notified about it. 

You mentioned "better notify the user if something fails". I'm working in 'Distraction-free mode', is that maybe the reason I'm not being notified?

**Comment by jlagerweij** [comment]
I tested the distraction free mode and get notifications if the tool fails. What changed is that the tool only parsed the output on exit code '2', but now always checks the outcome of the execution of the elm make task.

**Comment by jlagerweij** [comment]
To see more debug messages in the logs, do the following:
Use the menu Help -> Debug Log Settings...
Set or add a line with the content:  #org.elm.tools.external
Then change the Elm code and see the logfile. 
You can find the location of the log using the menu   Help -> Show Log in ...
The plugin should print a line like
2018-10-20 09:34:50,806 [1364936]  DEBUG - rnal.ElmExternalToolsComponent - 1 problems for file 

This is the last thing the plugin does. It hands the problems over to the editor for annotation.

**Comment by Birowsky** [comment]
Alright, thanx. Let's see what gives..

**Comment by Birowsky** [comment]
Here's the last time that thing shows in the logs:
```
2018-10-15 17:06:59,277 [13678228]   INFO - rnal.ElmExternalToolsComponent - /Users/../project-path: /usr/local/bin/elm make --report=json --output=/dev/null /Users/../SomeElmModule.elm 
```
There are a lot of logging after that, but none of it contains `rnal.ElmExternalToolsComponent`. Is this helpful? Or do you need more context around the logs? What do I look for? Do you want me to attach the whole thing?

**Comment by jlagerweij** [comment]
I was at least expecting a message containing 'Elm exit value: x' and since you mention it is not there, something is wrong when executing the 'elm make' command. Could you try to execute the command in the directory '/Users/../project-path' and see if that works?

**Comment by Birowsky** [comment]
> I was at least expecting a message containing 'Elm exit value: x' and since you mention it is not there, something is wrong when executing the 'elm make' command. Could you try to execute the command in the directory '/Users/../project-path' and see if that works?

Here's what I got:

```
/usr/local/bin/elm make --report=json --output=/dev/null /Users/../project-path/src/scripts/SomeModule.elm
[{"tag":"unused import","overview":"Module `Persistence` is unused.","details":"Best to remove it. Don't save code quality for later!","region":{"start":{"line":25,"column":1},"end":{"line":25,"column":19}},"type":"warning","file":"/Users/../project-path/src/scripts/SomeModule.elm"},{"tag":"missing type annotation","overview":"Top-level value `authRejectCmds` does not have a type annotation.","details":"I inferred the type annotation so you can copy it into your code:\n\nauthRejectCmds : Cmd msg","region":{"start":{"line":74,"column":1},"end":{"line":74,"column":15}},"type":"warning","file":"/Users/../proejct-path/src/scripts/SomeModule.elm"}]
Successfully generated /dev/null
```

Note that my project path is: `/Users/../project-path` 
and my entry Elm module path is: `project-path/src/scripts/MainModule.elm`
my `elm-package.json` is in the root folder: `project-path/`
and inside it, I have: `"source-directories": ["src/scripts"]`

**Comment by jlagerweij** [comment]
This is what I expected to see. There seems to be something wrong when executing the elm make command that makes it 'hang' somehow. The command itself does work, so there might be some PATH issue, but thats just guessing. The last thing I can think of trying is creating an entry in the IntelliJ settings under External Tools( Settings -> Tools -> External Tools) and add Elm Make there and then execute that External Tool to see what is the result. I suspect the way IntelliJ executes that External Tool is the same way my plugin executes it.

**Comment by Birowsky** [comment]
Hey, until I get around to do that, here's one that happens often. I would point out that the project compiles successfully.

<img width="376" alt="screen shot 2018-11-10 at 17 16 25" src="https://user-images.githubusercontent.com/3199950/48303628-a6773a80-e50c-11e8-85e0-31f3aabd74b2.png">

Is there a way for me to provide you with details around this message?
