### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by stejanse** [jlagerweij/elm-external-tools#6]
On save, the plug-in generates a NullPointerException on my system. Might have something to do with mixed up Elm version (0.18 code and 0.19 compiler).

```
annotator: org.elm.tools.external.annotator.ElmMakeExternalAnnotator@4f8dbd76 (class org.elm.tools.external.annotator.ElmMakeExternalAnnotator)

java.lang.NullPointerException
	at org.elm.tools.external.elmmake.ElmMake.parseCompileErrors(ElmMake.java:105)
	at org.elm.tools.external.elmmake.ElmMake.parseElmMakeOutput(ElmMake.java:77)
	at org.elm.tools.external.elmmake.ElmMake.execute(ElmMake.java:51)
	at org.elm.tools.external.annotator.ElmMakeExternalAnnotator.doAnnotate(ElmMakeExternalAnnotator.java:80)
	at org.elm.tools.external.annotator.ElmMakeExternalAnnotator.doAnnotate(ElmMakeExternalAnnotator.java:32)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:179)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:155)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:382)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jlagerweij** [comment]
Version 2.0.1 has just been released and will not gracefully let you know something is not right.
